sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - deps=""

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
  include:
    - php: 5.4
    - php: 5.4
      env: deps="low"
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.4.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.5.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x@dev"
    - php: 7.0
    - php: hhvm

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi
  - if [ "$deps" = "" ]; then composer install; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi
