sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - deps=""

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
    - php: 5.3
      env: deps="low"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x"
    - php: 5.6
      env: SYMFONY_VERSION="3.1.x"
    - php: 7.0
    - php: hhvm

before_install:
  - echo memory_limit = -1 >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$COVERAGE" != "yes" -a "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --dev --no-update; fi

install:
  - if [ "$deps" = "" ]; then composer install; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest --prefer-stable --prefer-dist; fi
